[package]
name = "token"
version = "0.1.0"


[dependencies]
starknet = "2.6.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.10.0" }

[[target.starknet-contract]]
casm = true
sierra = true
casm-add-pythonic-hints = true
