name: CI

permissions: read-all

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/kakarot-ssj/build.yml
    with:
      artifact-name: kakarot-ssj-build

  tests-unit:
    uses: ./.github/workflows/kakarot-ssj/tests-unit.yml
    with:
      run-fmt-check: true

  ef-tests:
    uses: ./.github/workflows/kakarot-ssj/ef-tests.yml
    needs: [build]
    with:
      artifact-name: kakarot-ssj-build
