# trunk-ignore-all(checkov/CKV2_GHA_1)
name: cairo-zero-Release

on:
  release:
    types: [published]
  # trunk-ignore(yamllint/empty-values)
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}/deployer

jobs:
  build_and_push_docker_deployer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags:
            ${{ env.REGISTRY_IMAGE }}:${{ github.ref_name }}, ${{
            env.REGISTRY_IMAGE }}:latest
          context: .
          file: ./docker/deployer/Dockerfile
          platforms: linux/amd64,linux/arm64

  build_and_push_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.14
      - uses: asdf-vm/actions/install@v3
      - run: asdf install
      - uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install dependencies
        run: make setup
      - name: Compile all the cairo files
        run: make build
      - name: Zip the build
        run: zip -r build.zip build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build.zip
          asset_name: kakarot-build.zip
          tag: ${{ github.ref_name }}
          overwrite: true
