name: SSJ-EF-Tests

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string

permissions: read-all

jobs:
  ef-tests:
    env:
      MLIR_SYS_190_PREFIX: /usr/lib/llvm-19/
      LLVM_SYS_191_PREFIX: /usr/lib/llvm-19/
      TABLEGEN_190_PREFIX: /usr/lib/llvm-19/
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: add llvm deb repository
        uses: myci-actions/add-deb-repo@11
        with:
          repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main
          repo-name: llvm-repo
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
      - name: Update and upgrade APT
        shell: bash
        run: sudo apt-get update && sudo apt-get upgrade -y
      - name: Install LLVM
        run:
          sudo apt-get install llvm-19 llvm-19-dev llvm-19-runtime clang-19
          clang-tools-19 lld-19 libpolly-19-dev libmlir-19-dev mlir-19-tools
          libgmp3-dev libzstd-dev lld libssl-dev zstd
      - name: Add llvm bin to PATH
        run: echo "/usr/lib/llvm-19/bin" >> $GITHUB_PATH

      - name: Checkout ef-tests
        uses: actions/checkout@v4
        with:
          repository: kkrt-labs/ef-tests
          path: ef-tests # Check out to a subdirectory to avoid cleaning the kakarot-ssj directory

      - name: Checkout local skip file
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            cairo/kakarot-ssj/
          sparse-checkout-cone-mode: false
          path: skip-file

      - name: Setup ef-tests
        run: |
          mv skip-file/cairo/kakarot-ssj/blockchain-tests-skip.yml ef-tests/blockchain-tests-skip.yml
          cd ef-tests
          mkdir -p build/common
          make setup setup-kakarot-v0

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Download Kakarot-SSJ build artifacts in v1
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ef-tests/build/v1

      - name: Move Cairo1Helpers
        run: |
          mv ef-tests/build/v1/contracts_Cairo1Helpers.compiled_contract_class.json \
          ef-tests/build/common/cairo1_helpers.json

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.14

      # Add this step to verify the file exists
      - name: Verify libcairo_native_runtime.a
        run: |
          echo $CAIRO_NATIVE_RUNTIME_LIBRARY
          ls -l $CAIRO_NATIVE_RUNTIME_LIBRARY

      - name: Run tests
        working-directory: ef-tests
        run: |
          set -o pipefail
          RUST_MIN_STACK=1342177280 make ef-test-v1-native | tee test_v1.out
          set +o pipefail

      - name: Retrieve ef-tests execution resources
        working-directory: ef-tests
        run: python scripts/compute_resources.py
        env:
          KAKAROT_VERSION: v1

      - name: Upload resources
        uses: actions/upload-artifact@v4
        with:
          path: ef-tests/resources
          name: resources

      - name: Generate blockchain-tests-skip.yml file
        if: github.event_name == 'workflow_dispatch'
        working-directory: ef-tests
        run: make generate-skip-file

      - name: Upload skip file
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          path: ef-tests/blockchain-tests-skip.yml
          name: blockchain-tests-skip
