name: SSJ-CI

permissions: read-all

on:
  pull_request:
    paths:
      - kakarot-ssj/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ssj-build:
    uses: ./.github/workflows/ssj-build.yml
    with:
      artifact-name: kakarot-ssj-build

  ssj-tests-unit:
    uses: ./.github/workflows/ssj-tests-unit.yml
    with:
      run-fmt-check: true

  ssj-ef-tests:
    uses: ./.github/workflows/ssj-ef-tests.yml
    needs: [ssj-build]
    with:
      artifact-name: kakarot-ssj-build
