name: SSJ-CI

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ssj-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      crates: ${{ steps.filter.outputs.crates }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            crates:
              - 'cairo/kakarot-ssj/crates/**'

  ssj-build:
    needs: paths-filter
    if: needs.paths-filter.outputs.crates == 'true'
    uses: ./.github/workflows/ssj-build.yml
    with:
      artifact-name: ssj-build

  ssj-tests-unit:
    needs: paths-filter
    if: needs.paths-filter.outputs.crates == 'true'
    uses: ./.github/workflows/ssj-tests-unit.yml
    with:
      run-fmt-check: false

  ssj-ef-tests:
    uses: ./.github/workflows/ssj-ef-tests.yml
    needs:
      - ssj-build
      - paths-filter
    if: needs.paths-filter.outputs.crates == 'true'
    with:
      artifact-name: ssj-build

  ssj-resources:
    runs-on: ubuntu-latest
    needs:
      - ssj-ef-tests
      - paths-filter
    if: needs.paths-filter.outputs.crates == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: make setup-ci

      - name: Load performance artifacts
        uses: actions/download-artifact@v3
        with:
          path: resources
          name: resources

      - name: Check resources evolution
        run: |
          result=$(GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} make check-resources 2>&1)
          echo "$result" >> "$GITHUB_STEP_SUMMARY"
