name: TESTS

on: [push, pull_request, pull_request_target]

jobs:
  compilation-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cairo-lang openzeppelin-cairo-contracts
      - name: Compile all the cairo files
        run: |
          for filename in $(find ./src/ -type f -name '*.cairo');
          do echo $(basename -- $filename) && starknet-compile $filename --cairo_path ./src --disable_hint_validation >/dev/null;
          done;

  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cairo-lang cairo-coverage pytest openzeppelin-cairo-contracts
      - name: Run tests
        run: |
          pytest 