name: Trunk

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  trunk_check:
    name: Trunk Check Runner
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.14
          cache: pip
      - run: pip install sympy==1.11.1 cairo-lang==0.13.1

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
